---
title: "warmup01-Yusheng-Xia.rmd"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



**Padme Amidala**
--------


>> "So this is how liberty dies... with thunderous applause"

| **Description** | **Value**  |
|-------------|--------|
| Species     | Human  |
| Gender      | Female |
| Eye Color   | Brown  |
| Skin Color  | Light  |


**Cooking Recipe: Crispy rice and egg bowl with ginger-scallion vinaigrette**
------


The crispy rice and egg bowl is a classic meal for summer workout months. It is both easy to make, healthy, and loaded with plenty of protein that guarantees energy, passion, and serenity for those lucky enough to experience a bite.

Ingredients

* 1 1/4 cups minced scallions, both green and white parts
* 2 tablespoons minced or finely grated fresh ginger
- Neutral oil (such as grapeseed, safflower, or sunflower)
- 1/4 cup sherry or rice wine vinegar
- Fine sea salt
- About 1 heaped cup julienned or coarsely grated carrots
- 8 ounces small (Persian-style, about 2) cucumbers, thinly sliced
- 3 cups cooked, cooled rice (my favorite here is short-grain brown or white)
- 4 eggs
- Soy sauce or tamari (to serve)
- Toasted sesame oil (to serve)
- Sriracha, gochujang or another hot sauce of your choice (to serve)

Tools

* Bowl
* Frying Pan
* Knife
* Whisk

Steps

1. Start with the dressing. Mix all your liquid ingredients with the scallions, salt, and other good stuff. Smell that delicious flavor emitting from the mixture and set it aside for later (if you can).

2. Heat up the bad boys. Turn the fire on and toast your pan to firey levels of hotness. Add on the oil, and when the pop pop pop sound of your personal mini bomb seems ready to explode, throw in the rice for some fine, fine cooking.

3. Take out rice, and throw in the eggs! Can leave our huevos out in the cold for long. You want them to be all nice and sunny side up, so that we can add a cheerful flavor into our creation.

4. Decoration time! With the rice in a bowl, toss in the carrots, cucumbers, and eggs just the way your mama taught you to. When everything looks all nice and dandy, sprinkle in your dressing and marvel at your wonderous creation that will leave Gordon Ramsay begging for a taste.

The cool thing about this recipe is that it is basically just a bunch of things thrown into a bowl. As a result, customize it however you want, use whatever ingredients you want, and cook it however you want. Basically, everybody has the opportunity to transform this recipe into their very own specialty.


**Assignment Part 3**
--------



**Definition** [edit] 

***
The **Euclidean distance** between points p and q is the length of the line segment connecting them (**\(\overline{\textbf{pq}}\)**).

In Cartesian coordinates, if **p** = (\(p_1, p_2, ... p_n\)) and **q** = (\(q_1, q_2, ... q_n\)) are two points in Euclidean *n*-space, then the distance (d) from **p** to **q**, or from **q** to **p** is given by the Pythagorean formula:
 
&nbsp;&nbsp;&nbsp; \(\textit{d}(\textbf{p},\textbf{q}) = \textit{d}(\textbf{q},\textbf{p}) = \sqrt[]{(q_1 - p_1)^2 + (q_2 - p_2)^2 + ... + (q_n - p_n)^2}\)
  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  \(= \sqrt[]{\displaystyle\sum_{i=1}^{n} (q_i - p_i)^2}\).
  
The position of a point in a Euclidean *n*-space is a Euclidean vector. So, **p** and **q** may be represented as Euclidean vectors, starting from the origin of the space (initial point) with their tips (terminal points) ending at the two points. The Euclidean norm, or **Euclidean length**, or **magnitude** of a vector measures the length of the vector:

&nbsp;&nbsp;&nbsp; \(\|\textbf{p}\| = \sqrt[]{p_1^2 + p_2^2 + ...+ p_n^2} = \sqrt[]{\textbf{p} \bullet \textbf{p}}\)

where the last expression involves dot product.







